services:
  pg:
    image: bitnami/postgresql:13.16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mygoals
    ports:
      - "5432:5432"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
